version: '3.5'
services:

#  tinkoff-adapter:
#    container_name: tinkoff_grpc
#    build:
#      context: .
#    depends_on:
#      - postgres1
#    restart: always
#    environment:
#      APP_PORT: ${APP_PORT}
#      DB_HOST: ${DB_HOST}
#      DB_PORT: ${DB_PORT}
#      DB_NAME: ${DB_NAME}
#      DB_USERNAME: ${DB_USERNAME}
#      DB_PASSWORD: ${DB_PASSWORD}
#      JVM_OPTS: >
#        -XX:+CrashOnOutOfMemoryError
#    networks:
#      - my_network
#    ports:
#      - 25224:8080
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 300M

networks:
  my_network: