spring:
  liquibase:
    change-log: classpath:db/changelog-master.xml
  application:
    name: tinkoff-provider
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: ${SHOW_SQL:false}
server:
  port: ${APP_PORT}
  error:
    include-message: always

logging:
#  config: classpath:log4j2.xml
  level:
    root: ${LOGGING_ROOT}
    ru.tinkoff.adapter: ${LOGGING_LEVEL}
    org.springframework.web: ${LOGGING_SPRING}
    feign.Logger: ${LOGGING_FEIGN}
    org.springframework.orm.jpa: ${LOGGING_JPA}
    org.springframework.transaction: ${LOGGING_TRANSACTIONS}
    org.hibernate.SQL: ${LOGGING_HIBERNATE}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOGGING_HIBERNATE}

integration:
  tinkoff:
    listener.enabled: true
    shares.listener.enabled: true
    emulator: false
    is-token-sandbox: false
    token-sandbox: ${TOKEN_SANDBOX}
    token-prom: ${TOKEN_PROM}
    account-id: ${ACCOUNT_ID}
    app-name: dmitry.temnikov
moexIss:
  url: http://localhost:24300


